
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 04 18:30:18 BRST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int t_LESS_THEN = 39;
  public static final int t_COLON = 20;
  public static final int t_IF = 9;
  public static final int t_END = 4;
  public static final int t_WHILE = 6;
  public static final int t_PARENTHESE_CLOSE = 28;
  public static final int t_DOTDOTDOT = 31;
  public static final int t_STRING = 49;
  public static final int t_GREATER_THEN = 41;
  public static final int t_LOCAL = 16;
  public static final int t_FALSE = 26;
  public static final int t_PLUS = 32;
  public static final int t_TRUE = 25;
  public static final int t_PERCENT = 37;
  public static final int t_LESS_EQUAL = 40;
  public static final int t_BRACKET_CLOSE = 23;
  public static final int EOF = 0;
  public static final int t_NAME = 51;
  public static final int t_FOR = 13;
  public static final int t_REPEAT = 7;
  public static final int error = 1;
  public static final int t_NOT_EQUAL = 44;
  public static final int t_NOT = 47;
  public static final int t_AND = 45;
  public static final int t_ELSE = 12;
  public static final int t_MINUS = 33;
  public static final int t_FUNCTION = 15;
  public static final int t_DO = 5;
  public static final int t_NIL = 24;
  public static final int t_ELSEIF = 11;
  public static final int t_THEN = 10;
  public static final int t_BLANK = 50;
  public static final int t_COMMA = 21;
  public static final int t_EXP = 36;
  public static final int t_SEMICOLON = 2;
  public static final int t_DOT = 19;
  public static final int t_DOTDOT = 38;
  public static final int t_UNTIL = 8;
  public static final int t_HASHTAG = 48;
  public static final int t_GREATER_EQUAL = 42;
  public static final int t_RETURN = 17;
  public static final int t_EQUAL = 43;
  public static final int t_BRACKET_OPEN = 22;
  public static final int t_BRACERS_OPEN = 29;
  public static final int t_NUMBER = 52;
  public static final int t_ATTRIBUTION = 3;
  public static final int t_BREAK = 18;
  public static final int t_BRACERS_CLOSE = 30;
  public static final int t_DEVIDED = 35;
  public static final int t_PARENTHESE_OPEN = 27;
  public static final int t_OR = 46;
  public static final int t_IN = 14;
  public static final int t_TIMES = 34;
}

