all:
	java -jar biblioteca/jflex-1.6.1.jar src/sintatico/lexer.flex
	java -jar biblioteca/java-cup-11a.jar -interface -parser Parser src/sintatico/Parser.cup

compile:
	javac -cp tools/java-cup-11a.jar *.java

run:
	java -cp tools/java-cup-11a.jar:. Main

clean:
	rm -rf *.class sym* Parser.java Scanner.java *~
