all:
	java -jar biblioteca/jflex-1.6.1.jar src/lexer.flex
	java -jar biblioteca/java-cup-11a.jar -parser Parser -destdir src src/parse.cup

compile:
	javac -cp biblioteca/java-cup-11a.jar src/sintatico/sym.java src/sintatico/Yylex.java src/sintatico/Parser.java

run:
	java -cp tools/java-cup-11a.jar:. Main

clean:
	rm -rf *.class sym* Parser.java Scanner.java *~
